services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    ports:
      - "4200:4200"

    command: npm start

    networks: 
      app-network:
        aliases:
          - angular-dev

networks:
  app-network:
    external: true
    name: app-network