services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    ports:
      - "4200:4200"

    command: npm start

    networks: 
      - app-network

networks:
  app-network:
    external: true